(custom/install-package-when-needed 'ido-vertical-mode)
(custom/install-package-when-needed 'flx-ido)
(custom/install-package-when-needed 'ido-completing-read+)
(require 'ido)
(require 'ido-vertical-mode)
(require 'ido-completing-read+)
(ido-mode t)
(ido-everywhere 1)
(ido-vertical-mode 1)
(setq ido-vertical-show-count t)
(setq ido-vertical-define-keys 'C-n-C-p-up-down-left-right)
(setq ido-enable-flex-matching t)
(flx-ido-mode 1)
(setq flx-ido-use-faces nil)
(ido-ubiquitous-mode 1)
