(custom/install-package-when-needed 'neotree)
(require 'neotree)
(setq neo-smart-open t)
(setq neo-theme 'ascii)
(setq projectile-switch-project-action 'neotree-projectile-action)
(defun neotree-startup ()
  (interactive)
  (neotree-show)
  (call-interactively 'other-window))
(if (daemonp)
    (add-hook 'server-switch-hook #'neotree-startup)
  (add-hook 'after-init-hook #'neotree-startup))
