(custom/install-package-when-needed 'smart-mode-line) 
(custom/install-package-when-needed 'smart-mode-line-powerline-theme)
(setq sml/no-confirm-load-theme t)
(setq sml/name-width 60)
(setq sml/mode-width 'full)
(sml/setup)
