;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-insert-or-skip-quote
        autopair-skip-close-maybe
        beginning-of-visual-line
        company-indent-or-complete-common
        cua--prefix-override-handler
        cua-paste
        custom/forward-symbol
        end-of-visual-line
        indent-for-tab-command
        keyboard-escape-quit
        markdown-cycle
        paredit-backward
        paredit-forward
        paredit-forward-down
        ))

(setq mc/cmds-to-run-once
      '(
        cua-copy-region
        cua-exchange-point-and-mark
        custom/copy-across-cursors
        custom/mc/mark-next-like-this
        custom/mc/mark-prev-like-this
        custom/spawn-cursor-bottom
        describe-key
        dired-unmark-backward
        find-function-on-key
        paredit-semicolon
        wdired-finish-edit
        ))
