;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        beginning-of-visual-line
        cua--prefix-override-handler
        cua-paste
        end-of-visual-line
        indent-for-tab-command
        keyboard-escape-quit
        paredit-backward
        paredit-forward
        paredit-forward-down
        ))

(setq mc/cmds-to-run-once
      '(
        cua-exchange-point-and-mark
        custom/mc/mark-next-like-this
        custom/mc/mark-prev-like-this
        custom/spawn-cursor-bottom
        describe-key
        find-function-on-key
        paredit-semicolon
        ))
