;; (package-initialize)
;; Placed here to make package manager happy and not insert
;; autogenerated shit here :(

;; set correct path separator
(if (eq system-type 'windows-nt)
    (setq custom/fs-separator "\\")
  (setq custom/fs-separator "/"))

;; set up EMACS custom settings file (used by UI settings manager)
(setq custom-file
      (concat (expand-file-name user-emacs-directory)
              "emacs-custom.el"))
(load custom-file)

;; set up EMACS C code tracking
(setq find-function-C-source-directory
      (concat (expand-file-name user-emacs-directory)
              "emacs-src"
              custom/fs-separator
              (substring (emacs-version) 10 14)
              custom/fs-separator
              "src"))

;; set up backup rules
(setq backup-directory-alist
      `(("." . ,(concat (expand-file-name user-emacs-directory)
                        "file-backups"))))
(setq delete-old-versions nil
      kept-new-versions 10
      kept-old-versions 10
      version-control t)

;; set up cygwin when running on windows
(if (eq system-type 'windows-nt)
    (progn
      (load "cygwin-mount.el")
      (require 'cygwin-mount)
      (cygwin-mount-activate)
      (load "setup-cygwin.el")
      (require 'setup-cygwin)))

(load (concat
       (expand-file-name user-emacs-directory)
       "sysdef.el"))
(sysdef/init)

(load "utils.el")
(load "package-loader.el")
(load "db.el")
(load "ui.el")
(load "keymap.el")
