(require 'cl)
(require 'package)
(require 'whitespace)

; Add MELPA repository
(package-initialize)
(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/"))
(add-to-list 'package-archives
             '("marmalade" . "http://marmalade-repo.org/packages/"))

(defun custom/install-package-when-needed (package)
  (unless (package-installed-p package)
     (progn (message "installing %s" package)
            (package-refresh-contents)
            (package-install package))))

(defun custom/setup-packages ()
  (load "f__.el")
  (load "visual-regex__.el")
  (load "spacemacs-theme__.el")
  (load "ace-jump-mode__.el")
  (load "ace-window__.el")
  (load "autopair__.el")
  (load "dired__.el")
  (load "elisp-slime-nav__.el")
  (load "idle-highlight__.el")
  (load "ido__.el")
  (load "minimap__.el")
  (load "neotree__.el")
  (load "paredit__.el")
  (load "projectile__.el")
  (load "smart-mode-line__.el")
  (load "undo-tree__.el")
  (load "ggtags__.el")
  (load "company__.el")
  (load "eldoc__.el")
  (load "imenu__.el")
  (load "imenu-list__.el")
  (load "semantic__.el")
  (load "eldoc-overlay__.el")
  (load "shackle__.el")
  (load "multiple-cursors__.el")
  (load "magit__.el"))
