(custom/install-package-when-needed 'visual-regexp)
(custom/install-package-when-needed 'visual-regexp-steroids)
(require 'visual-regexp)
(require 'visual-regexp-steroids)

(defun vr--set-target-buffer-start-end ()
      (setq vr--target-buffer-start (if (region-active-p)
                                        (region-beginning)
                                      (point-min)))
      (setq vr--target-buffer-end (if (region-active-p)
                                      (region-end)
                                    (point-max))))
